"""add leave_types.accrual_legal

Revision ID: 41174020e35a
Revises: 7c4f27a5d6e7
Create Date: 2026-08-28 19:38:47.825772

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '41174020e35a'
down_revision: Union[str, None] = '7c4f27a5d6e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default backfills existing rows (this table already has data in
    # any environment past first deploy) — autogenerate doesn't add this on
    # its own, only the model's Python-side default applies to new rows.
    op.add_column(
        "leave_types",
        sa.Column("accrual_legal", sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    op.alter_column("leave_types", "accrual_legal", server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('leave_types', 'accrual_legal')
    # ### end Alembic commands ###
