"""add attendance module and leave_types.code_court

Revision ID: 7222d653d23a
Revises: 9a3f1c2b7d4e
Create Date: 2026-09-01 15:24:20.015664

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '7222d653d23a'
down_revision: Union[str, None] = '9a3f1c2b7d4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attendance_codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('libelle', sa.String(length=60), nullable=False),
    sa.Column('code_court', sa.String(length=8), nullable=False),
    sa.Column('couleur', sa.String(length=20), nullable=False),
    sa.Column('compte_absence', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code_court'),
    sa.UniqueConstraint('libelle')
    )
    op.create_table('attendance_imports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom_fichier', sa.String(length=255), nullable=False),
    sa.Column('mois', sa.Integer(), nullable=False),
    sa.Column('annee', sa.Integer(), nullable=False),
    sa.Column('importe_par_user_id', sa.Integer(), nullable=False),
    sa.Column('nb_lignes_importees', sa.Integer(), nullable=False),
    sa.Column('nb_lignes_non_reconnues', sa.Integer(), nullable=False),
    sa.Column('noms_non_reconnus', sa.String(length=2000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['importe_par_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('attendance_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('code_id', sa.Integer(), nullable=True),
    sa.Column('valeur_brute', sa.String(length=60), nullable=True),
    sa.Column('import_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['code_id'], ['attendance_codes.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['import_id'], ['attendance_imports.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_id', 'date', name='uq_attendance_entries_employee_date')
    )
    op.create_index('ix_attendance_entries_date', 'attendance_entries', ['date'], unique=False)
    op.add_column('leave_types', sa.Column('code_court', sa.String(length=8), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('leave_types', 'code_court')
    op.drop_index('ix_attendance_entries_date', table_name='attendance_entries')
    op.drop_table('attendance_entries')
    op.drop_table('attendance_imports')
    op.drop_table('attendance_codes')
    # ### end Alembic commands ###
